#
# ██████╗░██╗░░░██╗  ███████╗███╗░░██╗░█████╗░░█████╗░░██████╗░
# ██╔══██╗╚██╗░██╔╝  ██╔════╝████╗░██║██╔══██╗██╔══██╗██╔════╝░
# ██████╦╝░╚████╔╝░  █████╗░░██╔██╗██║██║░░╚═╝██║░░██║██║░░██╗░
# ██╔══██╗░░╚██╔╝░░  ██╔══╝░░██║╚████║██║░░██╗██║░░██║██║░░╚██╗
# ██████╦╝░░░██║░░░  ███████╗██║░╚███║╚█████╔╝╚█████╔╝╚██████╔╝
# ╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚══╝░╚════╝░░╚════╝░░╚═════╝░
#
# Зелья
potions:
  speed_potion:
    name: "&6Зелье Флеша"
    description:
      - ""
      - "&fЭто зелье флеша,"
      - "&fвыпей и стань флешом!"
      - ""
    effects:
      - SPEED:600:2
    color: "FF0000"

  strength_potion:
    name: "&cЗелье Силача"
    description:
      - ""
      - "&fЭто зелье силача,"
      - "&fвыпей и стань силачом!"
      - ""
    effects:
      - INCREASE_DAMAGE:100:1
    color: "00FF00"

  healing_potion:
    name: "&bЗелье Лекаря"
    description:
      - ""
      - "&fЭто зелье лекаря,"
      - "&fвыпей и вылечись!"
      - ""
    effects:
      - HEAL:1:1
    color: "0000FF"

  multi_potion:
    name: "&dМульти зелье"
    description:
      - ""
      - "&fЭто мульти зелье,"
      - "&fвыпей его и познай силу!"
      - ""
    effects:
      - SPEED:600:2
      - INCREASE_DAMAGE:600:3
      - REGENERATION:600:1
    color: "FFFF00"
# Сообщения
messages:
  usage: "&6/engcpotions give <player> <potion_name> <amount>"
  player_not_found: "&cИгрок не найден."
  invalid_amount: "&cСумма должна быть числом."
  potion_not_found: "&cЗелье не найдено в конфиге"
  give_success: "&a{potion} выдано {player} в количестве {amount} шт."
