#
# ██████╗░██╗░░░██╗  ███████╗███╗░░██╗░█████╗░░█████╗░░██████╗░
# ██╔══██╗╚██╗░██╔╝  ██╔════╝████╗░██║██╔══██╗██╔══██╗██╔════╝░
# ██████╦╝░╚████╔╝░  █████╗░░██╔██╗██║██║░░╚═╝██║░░██║██║░░██╗░
# ██╔══██╗░░╚██╔╝░░  ██╔══╝░░██║╚████║██║░░██╗██║░░██║██║░░╚██╗
# ██████╦╝░░░██║░░░  ███████╗██║░╚███║╚█████╔╝╚█████╔╝╚██████╔╝
# ╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚══╝░╚════╝░░╚════╝░░╚═════╝░
#
# Зелья
potions:
  speed_potion:
    name: "&6Зелье Флеша"
    description:
      - ""
      - "&fЭто зелье флеша,"
      - "&fвыпей и стань флешом!"
      - ""
    effects:
      - SPEED:600:2
    color: "FF0000"

  strength_potion:
    name: "§cЗелье Силача"
    description:
      - ""
      - "§fЭто зелье силача,"
      - "§fвыпей и стань силачом!"
      - ""
    effects:
      - INCREASE_DAMAGE:100:1
    color: "00FF00"

  healing_potion:
    name: "&#15B1D9З&#23B7DCе&#31BDE0л&#3EC3E3ь&#4CC9E6е &#68D5EDЛ&#76DBF0е&#84E1F3к&#91E7F6а&#9FEDFAр&#ADF3FDя"
    description:
      - ""
      - "&#BAD1D7Э&#B9D3D9т&#B8D5DCо &#B7DAE1з&#B6DCE3е&#B5DEE5л&#B4E0E8ь&#B4E2EAе &#B2E6EFл&#B1E8F1е&#B0EBF4к&#AFEDF6а&#AFEFF8р&#AEF1FBя&#ADF3FD,"
      - "&#BAD1D7в&#B5D0D7ы&#B0D0D7п&#ABCFD7е&#A7CFD7й &#9DCED7и &#93CDD7в&#8ECCD6ы&#89CBD6л&#84CBD6е&#80CAD6ч&#7BCAD6и&#76C9D6с&#71C9D6ь&#6CC8D6!"
      - ""
    effects:
      - HEAL:1:1
    color: "0000FF"

  multi_potion:
    name: "&dМульти зелье"
    description:
      - ""
      - "&fЭто мульти зелье,"
      - "&fвыпей его и познай силу!"
      - ""
    effects:
      - SPEED:600:2
      - INCREASE_DAMAGE:600:3
      - REGENERATION:600:1
    color: "FFFF00"
# Сообщения
locale: ru # en